### ISSUE TITLE
Ask a question, Thanks.

### ISSUE THREAD

**Issue by zw963** [christopheraue/ruby-evdev#1]
I want to write a ruby program base on your's gem, which like following exist project:

https://github.com/kui/rbindkeys 
https://github.com/DreaminginCodeZH/pykeymacs

Could you give me some clue about which gem is used preferred?

Thanks.

**Comment by zw963** [comment]
Could you please explain about what difference about `1:1` version with this version?

**Comment by christopheraue** [comment]
> Could you give me some clue about which gem is used preferred?

You have to figure that out for yourself. You know best what you want to achieve.

> Could you please explain about what difference about 1:1 version with this version?

There is only one version of this gem.

**Comment by zw963** [comment]
What difference about `ruby-evdev` and `ruby-libevdev` ?

**Comment by christopheraue** [comment]
ruby-libevdev makes the functions of [libevdev](https://freedesktop.org/wiki/Software/libevdev/) available in ruby via FFI. So, it is as low level as libevdev with pointers, structs and so on.

ruby-evdev builds upon ruby-libevdev and let's you use it through a nicer, more object oriented API without the low level stuff. It does not wrap ruby-libevdev completely, though.

**Comment by zw963** [comment]
Hi, could you please give me some clue about how to add a handler for `CTRL+A`
and how to trigger this handler?

Lack of too much context, after some research, i still not understood this.

Thanks.

**Comment by zw963** [comment]
Is there a handler/hook make me can remap the event before

``` ruby
Libevdev.next_event(@device, Libevdev.const_get(:"READ_FLAG_#{mode.upcase}"), event.pointer)
```

is invoke? 

e.g. I want to remap `CTRL+F` to `CTRL+L`. 

Thanks.

**Comment by christopheraue** [comment]
> could you please give me some clue about how to add a handler for CTRL+A
> and how to trigger this handler?

```
event = LinuxInput::InputEvent.new
Libevdev.next_event(@device, Libevdev.const_get(:"READ_FLAG_#{mode.upcase}"), event.pointer)
```

populates `event` with a type, code and event. [This doc](https://www.kernel.org/doc/Documentation/input/event-codes.txt) explains the fields. To identify a `CTRL+A` you need to wait for the whole corresponding event chain to happen.

> remap the event before

evdev notifies you about device events coming from the kernel. To remap the events before being processed by the kernel you need to make sure the mapped event is the one sent to the kernel in the first place.

**Comment by zw963** [comment]
Thanks. although still not get the key idea.

I am refactoring [rbindkeys](https://github.com/kui/rbindkeys) now,
this project match all my need, although I am prefer `FFI` version.

I will try to understood the key idea about how to remap, and maybe
read your's reply again sometime.
