### ISSUE TITLE
best way to read events

### ISSUE THREAD

**Issue by xetum** [christopheraue/ruby-evdev#2]
What's the best way to read events and act only on digits (0-9) and RETURN? keyboard.on handlers? Libevdev.next_event? I'd like to rewrite in ruby the following evdev python code:

        self.dev.grab()
        uid = 0
        for event in self.dev.read_loop():
            if event.type == ecodes.EV_KEY and event.value == 0: # if keyevent and up
                if event.code == ecodes.KEY_ENTER: break
                uid = 10 * uid + (event.code - 1) % 10
        self.dev.ungrab()

Thanks

**Comment by christopheraue** [comment]
With a loop listening to the device's file and callbacks for each key you are interested in. For an example have a look at the [Event Handling section in the Readme](https://github.com/christopheraue/ruby-evdev/blob/master/README.md#event-handling).

`Evdev#handle_event` calls `Libevdev.next_event` under the hood: https://github.com/christopheraue/ruby-evdev/blob/2f5857ddb6ccf3deccd7afc2276e240dcc5e54bd/lib/evdev.rb#L88

**Comment by xetum** [comment]
I've read the README. But imagine you want to capture a fairly big set of keys and handle them in a unique handler. Something like:

    keyset_handler = kbd.on(event) do |value|
      if event[:code] == ...
        do_something
      end
    end

you don't want to set up the same handler for each keysym, do you?

**Comment by christopheraue** [comment]
Yes, you're right. That is not possible right now.

I'll take a look at how to extend the interface.

**Comment by christopheraue** [comment]
I released the changes as version 1.0.0. The interface is documented in the README.
