### ISSUE TITLE
Function 'libevdev_event_type_from_code_name' not found in [libevdev.so] (FFI::NotFoundError)

### ISSUE THREAD

**Issue by alxx** [christopheraue/ruby-evdev#5]
Hi, just trying a pristine gem installation on a fresh Raspberry Pi with Ruby 2.5.5 and I get this error right in the require line. I have libevdev 1.6.0 installed via apt (sudo apt install libevdev-dev).

Any tips?

**Comment by christopheraue** [comment]
This gem uses https://github.com/christopheraue/ruby-libevdev whose ffi has been generated with libevdev 1.9.0. Looks like `libevdev_event_type_from_code_name` was included rather recently in libevdev (https://gitlab.freedesktop.org/whot/libevdev/commit/774572d10559e3f3291bcb0f11e0dd7233b5df8c) and was not yet available in libevdev 1.6.0.

You could clone christopheraue/ruby-libevdev and regenerate the ffi based on your version of libevdev with `rake ffi:generate` . And then use your version of ruby-libevdev with this gem.

**Comment by alxx** [comment]
Ah, I see. I upgraded my libevdev and now your gem works fine. However, I don't understand how you could've used libevdev 1.9.0 when then last version I see on their [website](https://www.freedesktop.org/wiki/Software/libevdev/) is 1.8.0 from August 2019?

**Comment by christopheraue** [comment]
Looks like they didn't update their website yet. 1.9.0 was released at the beginning of march: https://lists.freedesktop.org/archives/input-tools/2020-March/001530.html.

**Comment by alxx** [comment]
Good to know. Thanks!
